# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh-service
spec:
  selector:
    app: ubuntu-ssh
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer

