apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

